DELETE FROM BRE.INCOMING_RISK_EVENTS;
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 100, sysdate, 0, 0, sysdate);
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 101, sysdate, 0, 0, sysdate);
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 102, sysdate, 0, 0, sysdate);
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 103, sysdate, 0, 0, sysdate);
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 104, sysdate, 0, 0, sysdate);
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 105, sysdate, 0, 0, sysdate);
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 106, sysdate, 0, 0, sysdate);
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 107, sysdate, 0, 0, sysdate);
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 108, sysdate, 0, 0, sysdate);
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 109, sysdate, 0, 0, sysdate);
INSERT INTO BRE.INCOMING_RISK_EVENTS(SYSTEM_ID, EVENT_CATEGORY_ID, IHUB_MERCHANT_ID, WORKER_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_TYPE_ID, EVENT_ID, TIME_DEQUEUED) VALUES(0, 0, 0, 0, 110, sysdate, 0, 0, sysdate);
COMMIT;

