SET DATABASE SQL SYNTAX ORA TRUE;
CREATE SCHEMA BRE;

--DROP TABLE BRE.INCOMING_RISK_EVENTS;
CREATE TABLE BRE.INCOMING_RISK_EVENTS 
(
	SYSTEM_ID     					INTEGER NOT NULL
	, EVENT_CATEGORY_ID				INTEGER NOT NULL
	, IHUB_MERCHANT_ID				BIGINT NOT NULL
	, WORKER_ID						INTEGER NOT NULL	
	, MERCHANT_ACCOUNT_NUMBER 		VARCHAR(64) NOT NULL
	, EVENT_DATE					DATE	
	, EVENT_TYPE_ID					INTEGER NOT NULL
	, EVENT_ID 						INTEGER NOT NULL
	, EVENT_DETAILS					VARCHAR(1024)	
	, RETRIES						INTEGER	DEFAULT -1 NOT NULL
	, PROCESSING_STATUS				INTEGER DEFAULT 0 NOT NULL 
	, ERROR_MSG						VARCHAR(4000) DEFAULT '' 
	, EVENT_TIMESTAMP				TIMESTAMP NOT NULL	
	, TIME_QUEUED					TIMESTAMP	
	, TIME_DE_QUEUED				TIMESTAMP NOT NULL
	, TIME_PROCESSED				TIMESTAMP
	, TIME_RETRY_1					TIMESTAMP
	, TIME_RETRY_2					TIMESTAMP
	, PRIMARY KEY(SYSTEM_ID, MERCHANT_ACCOUNT_NUMBER, EVENT_TIMESTAMP, EVENT_CATEGORY_ID, EVENT_TYPE_ID, EVENT_ID)
);

--DROP TABLE BRE.RISK_2_CONF;
CREATE TABLE BRE.RISK_2_CONF 
(
	KEY VARCHAR(128) NOT NULL
	, VALUE VARCHAR(1024) 
	, PRIMARY KEY(KEY)
);

--DROP TABLE BRE.MERCHANT_ALERTS;
CREATE TABLE BRE.MERCHANT_ALERTS
(
  EID                           INTEGER NOT NULL,
  MERCHANT_ACCOUNT_NUMBER       VARCHAR(64) NOT NULL,
  ALERT_TIMESTAMP               TIMESTAMP NOT NULL,
  BATCH_CYCLE_DATE              TIMESTAMP NOT NULL,
  CASE_TYPE                     VARCHAR(20 ),
  ALERT_TYPE                    VARCHAR(20 ),
  WORK_QUEUE                    VARCHAR(50 ),
  RULE_NAME                     VARCHAR(128) NOT NULL,
  RULE_VERSIONID                VARCHAR(20 ),
  RULE_DESCRIPTION              VARCHAR(2000 ),
  RULE_ACTUALVALUE              VARCHAR(2000 ),
  RULE_SET                      VARCHAR(2000 ),
  WORK_QUEUE_CATEGORY           VARCHAR(80 ),
  ALERT_STATUS                  VARCHAR(20 ),
  MERCHANT_EID                  INTEGER,
  SYSTEM_IDENTIFIER             VARCHAR(20 ),
  ALERT_IDENTIFIER              VARCHAR(50 ),
  PRIMARY KEY (MERCHANT_ACCOUNT_NUMBER, ALERT_TIMESTAMP, RULE_NAME)
);

